config/routes.rb
Rails.application.routes.draw do

  resources :images

  get "my_account" => "my_account#index"

  resources :charges, only: [:new, :create]

  post "charge_exisiting_card" => "charges#charge_existing"
 

  resources :cart_products, only: [:destroy]

  resources :orders do
    collection { get :index_admin }
  end

  resources :carts, only: [:update, :edit, :show, :destroy]

  resources :admin do
    collection { post :import }
  end

  resources :products, only: [:index, :show] do
    member { post "add_to_cart" => "carts#add_to_cart" }
  end
  resources :categories

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :profiles

  root to: "home#index"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :products, through: :cart_products
  has_many :cart_products, dependent: :destroy

  accepts_nested_attributes_for :cart_products


  # def add_product(product)
  #   products << product
  # end

  state_machine :state, initial: :empty do 

  event :add_product do
    transition empty: :loaded
  end

  event :check_out do
    transition loaded: :checked_out
  end

  event :cancel do
    transition loaded: :empty
  end

  end



  def add_product(product_id)
    if Product.find(product_id).in_stock?
      my_product = products.where('product_id = ?', product_id).first
      if my_product
        cp = cart_products.find_by_product_id(product_id)
        cp.quantity += 1
        cp.save
      else
        product = Product.find(product_id)
        products << product
      end
    end
  end


  def sub_total
    price = 0
    products.each do |product|
      price += (product.price.to_f * cart_products.find_by_product_id(product.id).quantity)
    end
    price.round(2)
  end


  def pst
    pst = 0
    pst = sub_total * 0.07
    pst.round(2)
  end

  def gst
    gst = 0
    gst = sub_total * 0.05
    gst.round(2)
  end

  def total_price
    (sub_total + pst + gst).round(2)
  end

  def in_cents
    (total_price * 100)
  end


  def cart_to_order
    list = {} 
    self.cart_products.each do |cp|
      list[cp.name] = {} 
      list[cp.name][:price] = cp.price
      list[cp.name][:quantity] = cp.quantity
    end
    list
  end

end

app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product

  delegate :name, to: :product
  delegate :price, to: :product

  validate :check_stocks, on: :update


  private


  def check_stocks
    if self.quantity > self.product.quantity.to_i
      errors.add(:base, "Not enough in stock!") 
    end
  end


end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products
  
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :product

  mount_uploader :image, ImageUploader
  
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user

  serialize :body

  scope :pending, -> { where(state: :pending) }
  scope :processing, -> { where(state: :processing) }
  scope :shipped, -> { where(state: :shipped) }
  scope :canceled, -> { where(state: :canceled) }

  state_machine :state, initial: :pending do 

    event :confirmed do
      transition pending: :processing
    end

    event :ship do
      transition processing: :shipped
    end

    event :cancel do
      transition [:pending, :processing] => :canceled
    end

  end

end

app/models/product.rb
require 'csv'

class Product < ActiveRecord::Base
  belongs_to :category
  has_many :carts, through: :cart_products
  has_many :cart_products
  has_many :images, dependent: :destroy
  validate :add_stocks, on: :update

  scope :draft, -> { where(state: :draft)}
  scope :off_shelves, -> { where(state: :off_shelves)}
  scope :sort_by_desc, -> {order("created_at DESC")}
  scope :product_for_sell, 
    -> { where("state LIKE 'in_stock' OR state LIKE 'sold_out'")}

  state_machine :state, initial: :draft do 

    event :product_ready_for_sell do
      transition [:draft, :sold_out] => :in_stock
    end

    event :inventory_sold_out do
      transition in_stock: :sold_out
    end

    event :remove_product do
      transition [:in_stock, :sold_out] => :off_shelves
    end

  end


  private

  def add_stocks
    if self.quantity == "0"
      errors.add(:base, "Cannot Add 0!") 
    end
  end


  def self.import(file)
    CSV.foreach(file.path, col_sep: ";", headers: true) do |row|
      Product.create! row.to_hash
    end
  end


  def self.search_by(search_term)
    where(["LOWER(name) LIKE :search_term OR
            LOWER(description) LIKE :search_term",
            {search_term: "%#{search_term.downcase}%"}]
         )
  end



end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates :user_id, uniqueness: true

  delegate :email, to: :user

  def full_name
    if first_name || last_name
      "#{first_name} #{last_name} ".squeeze(" ").strip
    else
      email
    end
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_one :profile, dependent: :destroy
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy


  delegate :full_name, to: :profile
  delegate :id, to: :profile, prefix: true

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end


end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
  :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/my_account_helper.rb
module MyAccountHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/edit.html.haml
%h1 Edit #{@product.name}
= simple_form_for @product, url: admin_path(@product) do |f|
  = f.input :name
  = f.input :description
  = f.input :price
  = f.input :quantity
  = f.input :category_id
  = f.submit "Save Product Info", class: "btn btn-info"

app/views/admin/index.html.haml
%h1 Product Index Page For Admin
%br
%hr
%h1 Import Your Products
= form_tag import_admin_index_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Import"
%hr
%h1 Your Products
%table.col-md-12.table.table-striped
  %tr.row
    %th Name
    %th Description
    %th Price
    %th Quantity
    %th Status
    %th Category
    %th Product ID
    %th Actions
  - @products.each do |product|
    %tr.row
      %td= link_to product.name, admin_path(product), method: :get
      %td= product.description
      %td= product.price
      %td= product.quantity
      %td= product.state
      %td= product.category.name
      %td= product.id
      %td
        = button_to "Delete", admin_path(product), method: :delete, data: {confirm: "Are you sure you want to delete #{product.name}?"}, class: "btn btn-danger"

  .row
  %td.text-center{colspan: "12"}
    = will_paginate @products, renderer: BootstrapPagination::Rails

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="root_path">FruityFruits</a> -->

      <%= link_to root_path do %>
        <span class="navbar-brand"><i class="icon-homepage"></i>FruityFruits</span>
      <% end %>

      <% if user_signed_in? %>
        <% if current_user.is_admin? %>
          <%= link_to "Orders", index_admin_orders_path, class: "navbar-brand" %>
          <%= link_to "Inventory", admin_index_path, class: "navbar-brand" %>
          <%= link_to "Product Images", images_path, class: "navbar-brand" %>
        <% end %>
      <% end %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Apples", categories_path(:type => 1) %></li>
            <li><%= link_to "Berries", categories_path(:type => 2) %></li>
            <li><%= link_to "Citrus", categories_path(:type => 3) %></li>
            <li><%= link_to "Olives", categories_path(:type => 4) %></li>
            <li><%= link_to "Grapes", categories_path(:type => 5) %></li>
            <li><%= link_to "Peaches", categories_path(:type => 6) %></li>
            <li><%= link_to "Melons", categories_path(:type => 7) %></li>
            <li><%= link_to "Pears", categories_path(:type => 8) %></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li>
            <%= link_to my_account_path, method: :get do %>
              <span><i class="icon-setting"></i>My Account</span>
            <% end %>
          </li>           
          <li>
            <%= link_to edit_cart_path(current_user.cart) do %>
              <i class="fa fa-shopping-cart"></i> Cart
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span><i class="icon-user"></i>Sign Out</span>
            <% end %>
          </li>
        <% else %>
          <li>
          <div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade" id="sign-in" role="dialog" tabindex="-1">
          <%= render "/home/sign_in" %>
          </div>
            <%= link_to "javascript:void(0);", "data-toggle" => "modal", "data-target" => "#sign-in" do %>
              <span><i class="icon-user"></i>Sign In</span>
            <% end %>
          </li>
        <% end %>

      </ul>
      <%= form_tag products_path, class: "navbar-form navbar-right", method: :get do %>
        <%= text_field_tag :search, @search_term %>
        <%= submit_tag "Search", class: "btn btn-default" %>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<div class="container-fluid">

  <%= yield %>

</div>
<br>
<footer class="footer">
  <div class="container">
    <div class="col-md-12">
      <div class="col-md-3 col-sm-3">
        <%= image_tag("fruity_fruits.png", class: "img-responsive center-block") %>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul>
          <h4> Product Area </h4>
          <li><%= link_to "Product 1", "#" %></li>
          <li> Product 2 </li>
          <li> Product 3 </li>
          <li> Product 4 </li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul>
          <h4> Links Group </h4>
          <li> Product 1 </li>
          <li> Product 2 </li>
          <li> Product 3 </li>
          <li> Product 4 </li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul>
          <h4> Cutsomer Service </h4>
          <li> Product 1 </li>
          <li> Product 2 </li>
          <li> Product 3 </li>
          <li> Product 4 </li>
        </ul>
      </div>
    </div>
    <div class="col-md-7 col-md-offset-5 links">
      <%= link_to "", "http://twitter.com", class: "icon-twitter footer-icon-size" %>
      <%= link_to "", "http://www.google.com", class: "icon-google footer-icon-size" %>
      <%= link_to "", "http://www.youtube.com", class: "icon-youtube footer-icon-size" %>
      <%= link_to "", "http://www.facebook.com", class: "icon-facebook footer-icon-size" %>
      <%= link_to "", "http://www.linkedin.com", class: "icon-linkedin footer-icon-size" %>
    </div>
    <div class="col-md-12">
      <div class="footer-text">
        All page content, graphics, website code and data are Copyrighted © FruityFruits 2014, All Rights Reserved. Some images are the property of their respective copyright holders.
      </div>
    </div>
  </div>
</footer>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="root_path">FruityFruits</a> -->

      <%= link_to root_path do %>
        <span class="navbar-brand"><i class="icon-homepage"></i>FruityFruits</span>
      <% end %>

      <% if user_signed_in? %>
        <% if current_user.is_admin? %>
          <%= link_to "Orders", index_admin_orders_path, class: "navbar-brand" %>
          <%= link_to "Inventory", admin_index_path, class: "navbar-brand" %>
          <%= link_to "Product Images", images_path, class: "navbar-brand" %>
        <% end %>
      <% end %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Apples", categories_path(:type => 1) %></li>
            <li><%= link_to "Berries", categories_path(:type => 2) %></li>
            <li><%= link_to "Citrus", categories_path(:type => 3) %></li>
            <li><%= link_to "Olives", categories_path(:type => 4) %></li>
            <li><%= link_to "Grapes", categories_path(:type => 5) %></li>
            <li><%= link_to "Peaches", categories_path(:type => 6) %></li>
            <li><%= link_to "Melons", categories_path(:type => 7) %></li>
            <li><%= link_to "Pears", categories_path(:type => 8) %></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li>
            <%= link_to my_account_path, method: :get do %>
              <span><i class="icon-setting"></i>My Account</span>
            <% end %>
          </li>           
          <li>
            <%= link_to edit_cart_path(current_user.cart) do %>
              <i class="fa fa-shopping-cart"></i> Cart
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span><i class="icon-user"></i>Sign Out</span>
            <% end %>
          </li>
        <% else %>
          <li>
          <div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade" id="sign-in" role="dialog" tabindex="-1">
          <%= render "/home/sign_in" %>
          </div>
            <%= link_to "javascript:void(0);", "data-toggle" => "modal", "data-target" => "#sign-in" do %>
              <span><i class="icon-user"></i>Sign In</span>
            <% end %>
          </li>
        <% end %>

      </ul>
      <%= form_tag products_path, class: "navbar-form navbar-right", method: :get do %>
        <%= text_field_tag :search, @search_term %>
        <%= submit_tag "Search", class: "btn btn-default" %>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<div class="container-fluid">
<div class="col-md-2 col-md-offset-1 hidden-xs">
  <div class= "row">
    <%= link_to( image_tag("http://i32.photobucket.com/albums/d36/stupidalex/ec-sh/BCfresh-Logo_zpsd37bb4aa.png", size:"250x100", class: "imgclass img-responsive center-block"), "http://bcfreshvegetables.com/" ) %>
  </div>
  <div class= "row">
    <%= link_to( image_tag("http://i32.photobucket.com/albums/d36/stupidalex/ec-sh/CPMA_zpsfa2120f7.png", size:"250x100", class: "imgclass img-responsive center-block"), "http://www.cpma.ca/" ) %>
  </div>
  <div class= "row">
    <%= link_to( image_tag("http://i32.photobucket.com/albums/d36/stupidalex/ec-sh/ifps_zps93d35163.png", size:"250x100", class: "imgclass img-responsive center-block"), "http://www.ifpsglobal.com/" ) %>
  </div>
  <div class= "row">
    <%= link_to( image_tag("http://i32.photobucket.com/albums/d36/stupidalex/ec-sh/CHC_zps84975746.jpg", size:"250x100", class: "imgclass img-responsive center-block"), "http://www.hortcouncil.ca/welcome-to-the-canadian-horticultural-council.aspx" ) %>
  </div>

</div>
<div class="col-md-9">
  <%= yield %>
</div>
</div>
<br>
<footer class="footer">
  <div class="container">
    <div class="col-md-12">
      <div class="col-md-3 col-sm-3">
        <%= image_tag("http://i32.photobucket.com/albums/d36/stupidalex/ec-sh/fruity_fruits_zps45522fbe.png", class: "img-responsive center-block") %>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul>
          <h4> Product Area </h4>
          <li><%= link_to "Product 1", "#" %></li>
          <li> Product 2 </li>
          <li> Product 3 </li>
          <li> Product 4 </li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul>
          <h4> Links Group </h4>
          <li> Product 1 </li>
          <li> Product 2 </li>
          <li> Product 3 </li>
          <li> Product 4 </li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul>
          <h4> Cutsomer Service </h4>
          <li> Product 1 </li>
          <li> Product 2 </li>
          <li> Product 3 </li>
          <li> Product 4 </li>
        </ul>
      </div>
    </div>
    <div class="col-md-7 col-md-offset-5 links col-xs-10 col-xs-offset-2">
      <%= link_to "", "http://twitter.com", class: "icon-twitter footer-icon-size" %>
      <%= link_to "", "http://www.google.com", class: "icon-google footer-icon-size" %>
      <%= link_to "", "http://www.youtube.com", class: "icon-youtube footer-icon-size" %>
      <%= link_to "", "http://www.facebook.com", class: "icon-facebook footer-icon-size" %>
      <%= link_to "", "http://www.linkedin.com", class: "icon-linkedin footer-icon-size" %>
    </div>
    <div class="col-md-12">
      <div class="footer-text">
        All page content, graphics, website code and data are Copyrighted © FruityFruits 2014, All Rights Reserved. Some images are the property of their respective copyright holders.
      </div>
    </div>
  </div>
</footer>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="root_path">FruityFruits</a> -->

      <%= link_to root_path do %>
        <span class="navbar-brand"><i class="icon-homepage"></i>FruityFruits</span>
      <% end %>

      <% if user_signed_in? %>
        <% if current_user.is_admin? %>
          <%= link_to "Orders", index_admin_orders_path, class: "navbar-brand" %>
          <%= link_to "Inventory", admin_index_path, class: "navbar-brand" %>
          <%= link_to "Product Images", images_path, class: "navbar-brand" %>
        <% end %>
      <% end %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Products <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Apples", categories_path(:type => 1) %></li>
            <li><%= link_to "Berries", categories_path(:type => 2) %></li>
            <li><%= link_to "Citrus", categories_path(:type => 3) %></li>
            <li><%= link_to "Olives", categories_path(:type => 4) %></li>
            <li><%= link_to "Grapes", categories_path(:type => 5) %></li>
            <li><%= link_to "Peaches", categories_path(:type => 6) %></li>
            <li><%= link_to "Melons", categories_path(:type => 7) %></li>
            <li><%= link_to "Pears", categories_path(:type => 8) %></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
          <li>
            <%= link_to my_account_path, method: :get do %>
              <span><i class="icon-setting"></i>My Account</span>
            <% end %>
          </li>           
          <li>
            <%= link_to edit_cart_path(current_user.cart) do %>
              <i class="fa fa-shopping-cart"></i> Cart
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <span><i class="icon-user"></i>Sign Out</span>
            <% end %>
          </li>
        <% else %>
          <li>
          <div aria-hidden="true" aria-labelledby="myModalLabel" class="modal fade" id="sign-in" role="dialog" tabindex="-1">
          <%= render "/home/sign_in" %>
          </div>
            <%= link_to "javascript:void(0);", "data-toggle" => "modal", "data-target" => "#sign-in" do %>
              <span><i class="icon-user"></i>Sign In</span>
            <% end %>
          </li>
        <% end %>

      </ul>
      <%= form_tag products_path, class: "navbar-form navbar-right", method: :get do %>
        <%= text_field_tag :search, @search_term %>
        <%= submit_tag "Search", class: "btn btn-default" %>
      <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<div class="container-fluid">
<div class="col-md-2 col-md-offset-1 hidden-xs">
  <div class= "row">
    <%= link_to( image_tag("http://i32.photobucket.com/albums/d36/stupidalex/ec-sh/BCfresh-Logo_zpsd37bb4aa.png", size:"250x100", class: "imgclass img-responsive center-block"), "http://bcfreshvegetables.com/" ) %>
  </div>
  <div class= "row">
    <%= link_to( image_tag("http://i32.photobucket.com/albums/d36/stupidalex/ec-sh/CPMA_zpsfa2120f7.png", size:"250x100", class: "imgclass img-responsive center-block"), "http://www.cpma.ca/" ) %>
  </div>
  <div class= "row">
    <%= link_to( image_tag("http://i32.photobucket.com/albums/d36/stupidalex/ec-sh/ifps_zps93d35163.png", size:"250x100", class: "imgclass img-responsive center-block"), "http://www.ifpsglobal.com/" ) %>
  </div>
  <div class= "row">
    <%= link_to( image_tag("http://i32.photobucket.com/albums/d36/stupidalex/ec-sh/CHC_zps84975746.jpg", size:"250x100", class: "imgclass img-responsive center-block"), "http://www.hortcouncil.ca/welcome-to-the-canadian-horticultural-council.aspx" ) %>
  </div>

</div>
<div class="col-md-9">
  <%= yield %>
</div>
</div>
<br>
<footer class="footer">
  <div class="container">
    <div class="col-md-12">
      <div class="col-md-3 col-sm-3">
        <%= image_tag("fruity_fruits.png", class: "img-responsive center-block") %>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul>
          <h4> Product Area </h4>
          <li><%= link_to "Product 1", "#" %></li>
          <li> Product 2 </li>
          <li> Product 3 </li>
          <li> Product 4 </li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul>
          <h4> Links Group </h4>
          <li> Product 1 </li>
          <li> Product 2 </li>
          <li> Product 3 </li>
          <li> Product 4 </li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3">
        <ul>
          <h4> Cutsomer Service </h4>
          <li> Product 1 </li>
          <li> Product 2 </li>
          <li> Product 3 </li>
          <li> Product 4 </li>
        </ul>
      </div>
    </div>
    <div class="col-md-7 col-md-offset-5 links">
      <%= link_to "", "http://twitter.com", class: "icon-twitter footer-icon-size" %>
      <%= link_to "", "http://www.google.com", class: "icon-google footer-icon-size" %>
      <%= link_to "", "http://www.youtube.com", class: "icon-youtube footer-icon-size" %>
      <%= link_to "", "http://www.facebook.com", class: "icon-facebook footer-icon-size" %>
      <%= link_to "", "http://www.linkedin.com", class: "icon-linkedin footer-icon-size" %>
    </div>
    <div class="col-md-12">
      <div class="footer-text">
        All page content, graphics, website code and data are Copyrighted © FruityFruits 2014, All Rights Reserved. Some images are the property of their respective copyright holders.
      </div>
    </div>
  </div>
</footer>

</body>
</html>