config/routes.rb
Rails.application.routes.draw do

  resources :images

  get "my_account" => "my_account#index"

  resources :charges, only: [:new, :create]

  post "charge_exisiting_card" => "charges#charge_existing"
 

  resources :cart_products, only: [:destroy]

  resources :orders do
    collection { get :index_admin }
  end

  resources :carts, only: [:update, :edit, :show, :destroy]

  resources :admin do
    collection { post :import }
  end

  resources :products, only: [:index, :show] do
    member { post "add_to_cart" => "carts#add_to_cart" }
  end
  resources :categories

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :profiles

  root to: "home#index"

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :products, through: :cart_products
  has_many :cart_products, dependent: :destroy

  accepts_nested_attributes_for :cart_products


  # def add_product(product)
  #   products << product
  # end

  state_machine :state, initial: :empty do 

  event :add_product do
    transition empty: :loaded
  end

  event :check_out do
    transition loaded: :checked_out
  end

  event :cancel do
    transition loaded: :empty
  end

  end



  def add_product(product_id)
    if Product.find(product_id).in_stock?
      my_product = products.where('product_id = ?', product_id).first
      if my_product
        cp = cart_products.find_by_product_id(product_id)
        cp.quantity += 1
        cp.save
      else
        product = Product.find(product_id)
        products << product
      end
    end
  end


  def sub_total
    price = 0
    products.each do |product|
      price += (product.price.to_f * cart_products.find_by_product_id(product.id).quantity)
    end
    price.round(2)
  end


  def pst
    pst = 0
    pst = sub_total * 0.07
    pst.round(2)
  end

  def gst
    gst = 0
    gst = sub_total * 0.05
    gst.round(2)
  end

  def total_price
    (sub_total + pst + gst).round(2)
  end

  def in_cents
    (total_price * 100)
  end


  def cart_to_order
    list = {} 
    self.cart_products.each do |cp|
      list[cp.name] = {} 
      list[cp.name][:price] = cp.price
      list[cp.name][:quantity] = cp.quantity
    end
    list
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def update
    @cart = current_user.cart
    if @cart.update(cart_attributes)
      redirect_to @cart
    else
      flash.now[:alert] = "#{@cart.errors.messages[:"cart_products.base"].join(" ,")}"
      render :edit
    end
  end

  def edit
    @cart = current_user.cart
  end

  def show
    @cart = current_user.cart
  end

  def destroy
    @cart = current_user.cart
    @cart_product = @cart.cart_products.find(params[:id])
    if @cart_product.destroy
      render
    else
      render :edit
    end
  end

  def add_to_cart
    product = Product.find(params[:id])
    if current_user.cart.add_product(params[:id])
      redirect_to product, notice: "Added To Your Cart"
    else
      redirect_to product, alert: "Failed to add to cart"
    end
  end

  private

  def cart_attributes
    params.require(:cart).permit({cart_products_attributes: [:quantity, :id]})
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
- if @cart.cart_products.present?
  #cart-edit
    = simple_form_for @cart, html: {class: "form-horizontal"} do |f|
      = f.fields_for :cart_products do |cp|
        .well
          .row
            .col-md-4
              = image_tag cp.object.product.images.first.image.url(:preview)
            .col-md-5
              %h4= cp.object.name
              %p
                $
                = cp.object.price
            .col-md-2
              = cp.input :quantity
            .col-md-1
              = link_to "", cart_path(cp.object), class: "btn btn-danger glyphicon glyphicon-remove", data: {confirm: "Do you want to remove this product from your cart?"}, method: :delete, remote: true
      = f.submit "Next ~>", class: "btn btn-info"
- else
  .well
    .row
      .col-md-12
        %h3 Your Cart Is Empty!
  

app/views/carts/destroy.js.haml
$("#cart-edit").html("#{j render 'cart'}");

app/views/carts/edit.html.haml
= render "cart"
  

app/views/carts/show.html.haml
%h1 Your Shopping Cart!


- @cart.products.each do |product|
  .well
    .row
      .col-md-10
        %h4
          Product Name:
          = product.name
        %p
          Price: $
          = product.price
      .col-md-2
        %h4 
          Qty:
          = @cart.cart_products.find_by_product_id(product.id).quantity



%h3 Your Sub Total: $#{@cart.sub_total}

= button_to "Check Out", new_charge_path, method: :get, class: "btn btn-default"
= button_to "Back", edit_cart_path(@cart), method: :get, class: "btn btn-default"