config/routes.rb
Rails.application.routes.draw do

  resources :images

  get "my_account" => "my_account#index"

  resources :charges, only: [:new, :create]

  post "charge_exisiting_card" => "charges#charge_existing"
 

  resources :cart_products, only: [:destroy]

  resources :orders do
    collection { get :index_admin }
  end

  resources :carts, only: [:update, :edit, :show, :destroy]

  resources :admin do
    collection { post :import }
  end

  resources :products, only: [:index, :show] do
    member { post "add_to_cart" => "carts#add_to_cart" }
  end
  resources :categories

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :profiles

  root to: "home#index"

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :authenticate_user!

  def new
    @cart = current_user.cart
  end

  def create
    @cart = current_user.cart
    # Amount in cents
    amount = @cart.in_cents.to_i
    @paid = @cart.total_price
    token = params[:stripeToken]

    if current_user.customer_id

      customer = Stripe::Customer.retrieve(current_user.customer_id)
      customer.card = token # obtained with Stripe.js
      customer.save

      charge = Stripe::Charge.create(
        :customer    => current_user.customer_id,
        :amount      => amount,
        :description => 'FruityFruits Stripe customer',
        :currency    => 'cad'
      )

    else
      customer = Stripe::Customer.create(
        :email => current_user.email,
        :card  => token
      )

      charge = Stripe::Charge.create(
        :customer    => customer.id,
        :amount      => amount,
        :description => 'FruityFruits Stripe customer',
        :currency    => 'cad'
      )

    end


    if charge.paid
      order = Order.new
      order.body = @cart.cart_to_order
      order.user = current_user
      order.order_number = "#{current_user.id}-#{Time.now.to_i}"
      order.paid = @paid
      order.save
      remove_product
      @cart.cart_products.destroy_all
      current_user.customer_id ||= customer.id
      current_user.stripe_card_last4 = customer.cards.data[0].last4
      current_user.stripe_card_type = customer.cards.data[0].type
      current_user.save
    end

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path

  end



  def charge_existing
    @cart = current_user.cart
    amount = @cart.in_cents.to_i
    @paid = @cart.total_price

    charge = Stripe::Charge.create(
      :customer    => current_user.customer_id,
      :amount      => amount,
      :description => 'FruityFruits Stripe customer',
      :currency    => 'cad'
    )

    if charge.paid
      order = Order.new
      order.body = @cart.cart_to_order
      order.user = current_user
      order.order_number = "#{current_user.id}-#{Time.now.to_i}"
      order.paid = @paid
      order.save 
      remove_product
      @cart.cart_products.destroy_all
    end

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end


  private

  def remove_product
    @cart.cart_products.each do |cp|
      stocks = cp.product.quantity.to_i
      final_stocks = stocks - cp.quantity
      if final_stocks.to_s == "0"
        cp.product.quantity = "Currently Sold Out!"
        cp.product.save
        cp.product.inventory_sold_out 
      else
        cp.product.quantity = final_stocks.to_s
        cp.product.save
      end
    end
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/charge_existing.html.haml
%h2
  Thanks, you paid
  = succeed "!" do
    %strong $ #{@paid}

app/views/charges/create.html.haml
%h2
  Thanks, you paid
  = succeed "!" do
    %strong $ #{@paid}

app/views/charges/new.html.haml
%h1 Check Out!

.jumbotron
  - @cart.products.each do |product|
    .well
      .row
        .col-md-10
          %h4
            Product Name:
            = product.name
          %p
            Price: $
            = product.price
        .col-md-2
          %h4 
            Qty:
            = @cart.cart_products.find_by_product_id(product.id).quantity
  %p Sub Total: $ #{@cart.sub_total}
  %p GST: $ #{@cart.gst}
  %p PST: $ #{@cart.pst}
  %p Total Amount: $ #{@cart.total_price}


= form_tag charges_path do
  %script.stripe-button{"data-billing-address" => true, "data-shipping-address" => true, "data-email" => "#{current_user.email}", "data-label" => "Pay with Stripe", "data-amount" => "#{@cart.in_cents}", "data-description" => "FruityFruits' Checkout!", "data-key" => Rails.configuration.stripe[:publishable_key], src: "https://checkout.stripe.com/checkout.js"}

%hr
- if current_user.customer_id
  .well
    = current_user.stripe_card_type
    **** **** **** #{current_user.stripe_card_last4}
    = button_to "Charge With This Card", charge_exisiting_card_path, class: "btn btn-primary", data: {confirm: "Are you sure you want to pay with this card?"}